apiVersion: v2
name: overcommit
description: overcommit
type: application
version: v0.1.0
appVersion: v0.1.0
keywords:
  - observing
  - arbiter
home: http://arbiter.k8s.com.cn
sources:
  - https://github.com/kube-arbiter/arbiter
maintainers:
  - name: nkwangleiGIT
    url: https://github.com/nkwangleiGIT
  - name: Abirdcfly
    url: https://github.com/Abirdcfly
  - name: 0xff-dev
    url: https://github.com/0xff-dev
  - name: pengcong08
    url: https://github.com/pengcong08
