apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-using-obi-adapter
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cpu-cost
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: External
    external:
      metricName: obi-cpu-metrics
      metricSelector: {}
      targetAverageValue: 500m
