apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
  labels:
    app: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: test
    spec:
      serviceAccountName: overcommit
      containers:
      - name: overcommit-webhook
        image: kubearbiter/webhook:v0.1.0
        command:
        - webhook
        ports:
        - containerPort: 9443
        volumeMounts:
        - name: overcommit-tls-secret
          mountPath: "/etc/webhook/certs"
          readOnly: true        
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 300m
            memory: 64Mi      
      volumes:
      - name: overcommit-tls-secret
        secret:
          secretName: overcommit-tls-secret
