apiVersion: v1
kind: ServiceAccount
metadata:
  name: overcommit
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: overcommit
rules:
- apiGroups:
  - arbiter.k8s.com.cn
  resources:
  - overcommits
  verbs:
  - create
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: overcommit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: overcommit
subjects:
- kind: ServiceAccount
  name: overcommit
  namespace: {{ .Release.Namespace }}
