apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.overCommit.serviceName }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: overcommit-webhook
  ports:
  - protocol: TCP
    port: {{ .Values.overCommit.port }}
    targetPort: {{ .Values.overCommit.port }}
