apiVersion: apps/v1
kind: Deployment
metadata:
  name: observer-server
spec:
  selector:
    matchLabels:
      app: observer-server
  template:
    metadata:
      labels:
        app: observer-server
    spec:
      containers:
        - command:
            - observer-default-plugins
            - -address=http://prometheus-server.kube-system.svc.cluster.local
            - -v=4
          image: kubearbiter/observer-default-plugins:v0.2.0
          name: observer-plugins
          livenessProbe:
            exec:
              command: ["/bin/sh", "-c", "echo 'hello'|nc local:/var/run/observer.sock"]
          resources:
            limits:
              cpu: 1
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 64Mi
          volumeMounts:
            - mountPath: /var/run
              name: sock-volume
        - command:
            - observer
          image: kubearbiter/observer:v0.2.0
          name: observer-controller
          resources:
            limits:
              cpu: 1
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 64Mi
          volumeMounts:
            - mountPath: /var/run
              name: sock-volume
      serviceAccount: observability
      serviceAccountName: observability
      volumes:
        - emptyDir: {}
          name: sock-volume
